#spring:
#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          # 用于向令牌侦测端点进行身份验证的客户端 ID。
#          client-id: mz_cloud
#          client-secret: 1911298402
#          introspection-uri: http://localhost:9000/oauth/check_token
security:
  oauth2:
    client:
      client-id: mz_cloud
      client-secret: 1911298402
      user-authorization-uri: http://localhost:9000/oauth/authorize
      access-token-uri: http://localhost:9000/oauth/token
    resource:
      token-info-uri: http://localhost:9000/oauth/check_token
server:
  servlet:
    session:
      cookie:
        name: MZ_CLOUD_SESSION_SYS
#        user-info-uri: http://localhost:8081/user