# 应用名称
spring:
  application:
    name: mz-common-gateway-provider
  swagger:
    author:
      name: 小政同学i丷
      email: xiaozheng666888@qq.com
    api-info:
      title: mz-cloud接口文档
      version: v1.0

  # redis 配置
  redis:
    host: ${REDIS_HOST:192.168.56.2}
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8   # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接
        time-between-eviction-runs: 100 # 连接超时时间（毫秒）
  cloud:
    gateway:
      enabled: true
      # 注意跳转条件的优先级
      routes:
        - id: mz-system-provider
          uri: lb://mz-system-provider
          predicates:
            - Path=/api/system/**
          # 将api删掉
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
      # 是否启用新端点
      actuator:
        verbose:
          enabled: false
server:
  port: 88
# 网关可控点Api开启
management:
  endpoints:
    web:
      exposure:
        include: gateway

